# DO NOT DELETE: Beginning of Haskell dependencies
BootChild._o_ : children/BootChild.hs
BootChild._o_ : C:/ghc/ghc-7.6.3/lib/base-4.6.0.1/Prelude.hi
HsBoot._o_-boot : HsBoot.hs-boot
HsBoot._o_-boot : C:/ghc/ghc-7.6.3/lib/base-4.6.0.1/Prelude.hi
HsBoot._o_-boot : BootChild._hi_
LhsBoot._o_-boot : LhsBoot.lhs-boot
LhsBoot._o_-boot : C:/ghc/ghc-7.6.3/lib/base-4.6.0.1/Prelude.hi
IncludeChild._o_ : children/IncludeChild.hs
IncludeChild._o_ : C:/ghc/ghc-7.6.3/lib/base-4.6.0.1/Prelude.hi
Lhs._o_ : Lhs.lhs
Lhs._o_ : C:/ghc/ghc-7.6.3/lib/base-4.6.0.1/Prelude.hi
Include._o_ : Include.hs
Include._o_ : C:/ghc/ghc-7.6.3/lib/base-4.6.0.1/Prelude.hi
Include._o_ : IncludeChild._hi_
LhsRec._o_ : LhsRec.lhs
LhsRec._o_ : LhsBoot._hi_-boot
LhsRec._o_ : C:/ghc/ghc-7.6.3/lib/base-4.6.0.1/Prelude.hi
LhsBoot._o_ : LhsBoot.lhs
LhsBoot._o_ : C:/ghc/ghc-7.6.3/lib/base-4.6.0.1/Prelude.hi
LhsBoot._o_ : LhsRec._hi_
HsRec._o_ : HsRec.hs
HsRec._o_ : HsBoot._hi_-boot
HsRec._o_ : C:/ghc/ghc-7.6.3/lib/base-4.6.0.1/Prelude.hi
HsBoot._o_ : HsBoot.hs
HsBoot._o_ : C:/ghc/ghc-7.6.3/lib/base-4.6.0.1/Prelude.hi
HsBoot._o_ : BootChild._hi_
HsBoot._o_ : HsRec._hi_
Main._o_ : Root.hs
Main._o_ : C:/ghc/ghc-7.6.3/lib/base-4.6.0.1/Prelude.hi
Main._o_ : Lhs._hi_
Main._o_ : Include._hi_
Main._o_ : LhsRec._hi_
Main._o_ : HsRec._hi_
# DO NOT DELETE: End of Haskell dependencies
